language: csharp
mono: none
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
after_script:
  - bash <(curl -s https://codecov.io/bash)
