using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Tti.Estate.Data.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "County",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Code = table.Column<string>(maxLength: 50, nullable: false),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_County", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                });

            migrationBuilder.CreateTable(
                name: "User",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Role = table.Column<int>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    UserName = table.Column<string>(maxLength: 256, nullable: false),
                    PasswordHash = table.Column<string>(nullable: false),
                    FirstName = table.Column<string>(maxLength: 50, nullable: false),
                    LastName = table.Column<string>(maxLength: 50, nullable: false),
                    Telephone = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_User", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                });

            migrationBuilder.CreateTable(
                name: "City",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Code = table.Column<string>(maxLength: 50, nullable: false),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    CountyId = table.Column<long>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_City", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_City_County_CountyId",
                        column: x => x.CountyId,
                        principalTable: "County",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Customer",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    UserId = table.Column<long>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    Created = table.Column<DateTime>(nullable: false),
                    Modified = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customer", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Customer_User_UserId",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Property",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    UserId = table.Column<long>(nullable: false),
                    PropertyType = table.Column<int>(nullable: false),
                    TransactionType = table.Column<int>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    Price = table.Column<decimal>(type: "decimal(12,2)", nullable: false),
                    HasVat = table.Column<bool>(nullable: false, defaultValue: false),
                    CountyId = table.Column<long>(nullable: false),
                    CityId = table.Column<long>(nullable: false),
                    Street = table.Column<string>(maxLength: 64, nullable: true),
                    HouseNumber = table.Column<string>(maxLength: 8, nullable: true),
                    ApartmentNumber = table.Column<string>(maxLength: 8, nullable: true),
                    CadastralNumber = table.Column<string>(maxLength: 128, nullable: true),
                    Area = table.Column<decimal>(type: "decimal(5,2)", nullable: false),
                    LandArea = table.Column<decimal>(type: "decimal(5,2)", nullable: true),
                    FloorCount = table.Column<byte>(nullable: true),
                    Floor = table.Column<byte>(nullable: true),
                    RoomCount = table.Column<byte>(nullable: true),
                    IsRestricted = table.Column<bool>(nullable: false, defaultValue: false),
                    Description = table.Column<string>(nullable: true),
                    Created = table.Column<DateTime>(nullable: false),
                    Modified = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Property", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Property_City_CityId",
                        column: x => x.CityId,
                        principalTable: "City",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Property_County_CountyId",
                        column: x => x.CountyId,
                        principalTable: "County",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Property_User_UserId",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Contact",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    PropertyId = table.Column<long>(nullable: true),
                    CustomerId = table.Column<long>(nullable: true),
                    FirstName = table.Column<string>(maxLength: 50, nullable: false),
                    LastName = table.Column<string>(maxLength: 50, nullable: true),
                    Telephone = table.Column<string>(maxLength: 50, nullable: false),
                    Email = table.Column<string>(maxLength: 254, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Contact", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Contact_Customer_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "Customer",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Contact_Property_PropertyId",
                        column: x => x.PropertyId,
                        principalTable: "Property",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Photo",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    PropertyId = table.Column<long>(nullable: false),
                    IsDefault = table.Column<bool>(nullable: false, defaultValue: false),
                    ExternalId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Photo", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Photo_Property_PropertyId",
                        column: x => x.PropertyId,
                        principalTable: "Property",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Transaction",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    UserId = table.Column<long>(nullable: false),
                    TransactionType = table.Column<int>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    PropertyId = table.Column<long>(nullable: false),
                    CustomerId = table.Column<long>(nullable: false),
                    Date = table.Column<DateTime>(nullable: false),
                    Amount = table.Column<decimal>(type: "decimal(12,2)", nullable: false),
                    CompanyPercent = table.Column<byte>(nullable: false),
                    UserPercent = table.Column<byte>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    Created = table.Column<DateTime>(nullable: false),
                    Modified = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Transaction", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Transaction_Customer_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "Customer",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Transaction_Property_PropertyId",
                        column: x => x.PropertyId,
                        principalTable: "Property",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Transaction_User_UserId",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Comment",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    UserId = table.Column<long>(nullable: false),
                    PropertyId = table.Column<long>(nullable: true),
                    CustomerId = table.Column<long>(nullable: true),
                    TransactionId = table.Column<long>(nullable: true),
                    Text = table.Column<string>(nullable: false),
                    Created = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Comment", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_Comment_Customer_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "Customer",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Comment_Property_PropertyId",
                        column: x => x.PropertyId,
                        principalTable: "Property",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Comment_Transaction_TransactionId",
                        column: x => x.TransactionId,
                        principalTable: "Transaction",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Comment_User_UserId",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "County",
                columns: new[] { "Id", "Code", "Name" },
                values: new object[,]
                {
                    { 2L, "RIGA", "Rīga" },
                    { 174L, "RUNDALES_NOV", "Rundāles nov." },
                    { 172L, "RUGAJU_NOV", "Rugāju nov." },
                    { 170L, "RUCAVAS_NOV", "Rucavas nov." },
                    { 168L, "REZEKNES_NOV", "Rēzeknes nov." },
                    { 166L, "PRIEKULU_NOV", "Priekuļu nov." },
                    { 164L, "PRIEKULES_NOV", "Priekules nov." },
                    { 162L, "PLAVINU_NOV", "Pļaviņu nov." },
                    { 160L, "PAVILOSTAS_NOV", "Pāvilostas nov." },
                    { 158L, "PARGAUJAS_NOV", "Pārgaujas nov." },
                    { 156L, "OLAINES_NOV", "Olaines nov." },
                    { 154L, "NICAS_NOV", "Nīcas nov." },
                    { 152L, "NERETAS_NOV", "Neretas nov." },
                    { 176L, "RUJIENAS_NOV", "Rūjienas nov." },
                    { 150L, "NAUKSENU_NOV", "Naukšēnu nov." },
                    { 146L, "MARUPES_NOV", "Mārupes nov." },
                    { 144L, "MALPILS_NOV", "Mālpils nov." },
                    { 142L, "MADONAS_NOV", "Madonas nov." },
                    { 140L, "LUDZAS_NOV", "Ludzas nov." },
                    { 138L, "LIMBAZU_NOV", "Limbažu nov." },
                    { 136L, "LIGATNES_NOV", "Līgatnes nov." },
                    { 134L, "KEKAVAS_NOV", "Ķekavas nov." },
                    { 132L, "KULDIGAS_NOV", "Kuldīgas nov." },
                    { 130L, "KRUSTPILS_NOV", "Krustpils nov." },
                    { 128L, "KRIMULDAS_NOV", "Krimuldas nov." },
                    { 126L, "KOKNESES_NOV", "Kokneses nov." },
                    { 124L, "KARSAVAS_NOV", "Kārsavas nov." },
                    { 148L, "MAZSALACAS_NOV", "Mazsalacas nov." },
                    { 122L, "JELGAVAS_NOV", "Jelgavas nov." },
                    { 178L, "SALACGRIVAS_NOV", "Salacgrīvas nov." },
                    { 182L, "SALDUS_NOV", "Saldus nov." },
                    { 234L, "RIEBINU_NOV", "Riebiņu nov." },
                    { 232L, "ROPAZU_NOV", "Ropažu nov." },
                    { 230L, "LIELVARDES_NOV", "Lielvārdes nov." },
                    { 228L, "RAUNAS_NOV", "Raunas nov." },
                    { 226L, "SAULKRASTU_NOV", "Saulkrastu nov." },
                    { 224L, "JAUNPIEBALGAS_NOV", "Jaunpiebalgas nov." },
                    { 222L, "INCUKALNA_NOV", "Inčukalna nov." },
                    { 220L, "SEJAS_NOV", "Sējas nov." },
                    { 218L, "ERGLU_NOV", "Ērgļu nov." },
                    { 216L, "BURTNIEKU_NOV", "Burtnieku nov." },
                    { 214L, "VILANU_NOV", "Viļānu nov." },
                    { 212L, "VILAKAS_NOV", "Viļakas nov." },
                    { 180L, "SALAS_NOV", "Salas nov." },
                    { 210L, "VIESITES_NOV", "Viesītes nov." },
                    { 206L, "VECUMNIEKU_NOV", "Vecumnieku nov." },
                    { 204L, "VECPIEBALGAS_NOV", "Vecpiebalgas nov." },
                    { 202L, "VARAKLANU_NOV", "Varakļānu nov." },
                    { 200L, "KOCENU_NOV", "Kocēnu nov." },
                    { 198L, "VALKAS_NOV", "Valkas nov." },
                    { 196L, "VAINODES_NOV", "Vaiņodes nov." },
                    { 194L, "TUKUMA_NOV", "Tukuma nov." },
                    { 192L, "TALSU_NOV", "Talsu nov." },
                    { 190L, "STRENCU_NOV", "Strenču nov." },
                    { 188L, "SMILTENES_NOV", "Smiltenes nov." },
                    { 186L, "SKRUNDAS_NOV", "Skrundas nov." },
                    { 184L, "SKRIVERU_NOV", "Skrīveru nov." },
                    { 208L, "VENTSPILS_NOV", "Ventspils nov." },
                    { 236L, "STOPINU_NOV", "Stopiņu nov." },
                    { 120L, "JEKABPILS_NOV", "Jēkabpils nov." },
                    { 116L, "JAUNJELGAVAS_NOV", "Jaunjelgavas nov." },
                    { 54L, "ILUKSTES_NOV", "Ilūkstes nov." },
                    { 52L, "SIGULDAS_NOV", "Siguldas nov." },
                    { 50L, "KANDAVAS_NOV", "Kandavas nov." },
                    { 48L, "OZOLNIEKU_NOV", "Ozolnieku nov." },
                    { 46L, "ZILUPES_NOV", "Zilupes nov." },
                    { 44L, "TERVETES_NOV", "Tērvetes nov." },
                    { 42L, "OGRES_NOV", "Ogres nov." },
                    { 40L, "IECAVAS_NOV", "Iecavas nov." },
                    { 38L, "KEGUMA_NOV", "Ķeguma nov." },
                    { 36L, "LIVANU_NOV", "Līvānu nov." },
                    { 34L, "VARKAVAS_NOV", "Vārkavas nov." },
                    { 32L, "DURBES_NOV", "Durbes nov." },
                    { 56L, "IKSKILES_NOV", "Ikšķiles nov." },
                    { 30L, "PREILU_NOV", "Preiļu nov." },
                    { 26L, "KRASLAVAS_NOV", "Krāslavas nov." },
                    { 24L, "AIZKRAUKLES_NOV", "Aizkraukles nov." },
                    { 22L, "AMATAS_NOV", "Amatas nov." },
                    { 20L, "CIBLAS_NOV", "Ciblas nov." },
                    { 18L, "JEKABPILS", "Jēkabpils" },
                    { 16L, "VALMIERA", "Valmiera" },
                    { 14L, "REZEKNE", "Rēzekne" },
                    { 12L, "DAUGAVPILS", "Daugavpils" },
                    { 10L, "JURMALA", "Jūrmala" },
                    { 8L, "VENTSPILS", "Ventspils" },
                    { 6L, "LIEPAJA", "Liepāja" },
                    { 4L, "JELGAVA", "Jelgava" },
                    { 28L, "BROCENU_NOV", "Brocēnu nov." },
                    { 118L, "JAUNPILS_NOV", "Jaunpils nov." },
                    { 58L, "AGLONAS_NOV", "Aglonas nov." },
                    { 62L, "AKNISTES_NOV", "Aknīstes nov." },
                    { 114L, "GULBENES_NOV", "Gulbenes nov." },
                    { 112L, "GROBINAS_NOV", "Grobiņas nov." },
                    { 110L, "ENGURES_NOV", "Engures nov." },
                    { 108L, "DUNDAGAS_NOV", "Dundagas nov." },
                    { 106L, "DOBELES_NOV", "Dobeles nov." },
                    { 104L, "DAUGAVPILS_NOV", "Daugavpils nov." },
                    { 102L, "DAGDAS_NOV", "Dagdas nov." },
                    { 100L, "CESVAINES_NOV", "Cesvaines nov." },
                    { 98L, "CESU_NOV", "Cēsu nov." },
                    { 96L, "BEVERINAS_NOV", "Beverīnas nov." },
                    { 94L, "BAUSKAS_NOV", "Bauskas nov." },
                    { 92L, "BALVU_NOV", "Balvu nov." },
                    { 60L, "AIZPUTES_NOV", "Aizputes nov." },
                    { 90L, "BALTINAVAS_NOV", "Baltinavas nov." },
                    { 86L, "AUCES_NOV", "Auces nov." },
                    { 84L, "BALDONES_NOV", "Baldones nov." },
                    { 82L, "MERSRAGA_NOV", "Mērsraga nov." },
                    { 80L, "ROJAS_NOV", "Rojas nov." },
                    { 78L, "GARKALNES_NOV", "Garkalnes nov." },
                    { 76L, "CARNIKAVAS_NOV", "Carnikavas nov." },
                    { 74L, "ADAZU_NOV", "Ādažu nov." },
                    { 72L, "LUBANAS_NOV", "Lubānas nov." },
                    { 70L, "APES_NOV", "Apes nov." },
                    { 68L, "ALUKSNES_NOV", "Alūksnes nov." },
                    { 66L, "ALSUNGAS_NOV", "Alsungas nov." },
                    { 64L, "ALOJAS_NOV", "Alojas nov." },
                    { 88L, "BABITES_NOV", "Babītes nov." },
                    { 238L, "SALASPILS_NOV", "Salaspils nov." }
                });

            migrationBuilder.InsertData(
                table: "City",
                columns: new[] { "Id", "Code", "CountyId", "Name" },
                values: new object[,]
                {
                    { 1L, "AGENSKALNS", 2L, "Āgenskalns" },
                    { 544L, "ZALVES_PAG", 152L, "Zalves pag." },
                    { 545L, "MAZZALVES_PAG", 152L, "Mazzalves pag." },
                    { 546L, "NERETA", 152L, "Nereta" },
                    { 547L, "NICAS_PAG", 154L, "Nīcas pag." },
                    { 548L, "OTANKU_PAG", 154L, "Otaņķu pag." },
                    { 549L, "OLAINE", 156L, "Olaine" },
                    { 550L, "OLAINES_PAG", 156L, "Olaines pag." },
                    { 551L, "JAUNOLAINE", 156L, "Jaunolaine" },
                    { 552L, "PAROLAINE", 156L, "Pārolaine" },
                    { 553L, "STUNISI", 156L, "Stūnīši" },
                    { 554L, "GRENES", 156L, "Grēnes" },
                    { 555L, "STALBES_PAG", 158L, "Stalbes pag." },
                    { 556L, "RAISKUMA_PAG", 158L, "Raiskuma pag." },
                    { 557L, "STRAUPES_PAG", 158L, "Straupes pag." },
                    { 558L, "PAVILOSTA", 160L, "Pāvilosta" },
                    { 559L, "SAKAS_PAG", 160L, "Sakas pag." },
                    { 560L, "VERGALES_PAG", 160L, "Vērgales pag." },
                    { 561L, "PLAVINAS", 162L, "Pļaviņas" },
                    { 562L, "KLINTAINES_PAG", 162L, "Klintaines pag." },
                    { 563L, "VIETALVAS_PAG", 162L, "Vietalvas pag." },
                    { 564L, "AIVIEKSTES_PAG", 162L, "Aiviekstes pag." },
                    { 543L, "PILSKALNES_NERETAS", 152L, "Pilskalnes pag." },
                    { 542L, "NERETAS_PAG", 152L, "Neretas pag." },
                    { 541L, "NAUKSENU_PAG", 150L, "Naukšēnu pag." },
                    { 540L, "KONU_PAG", 150L, "Ķoņu pag." },
                    { 518L, "PRAULIENAS_PAG", 142L, "Praulienas pag." },
                    { 519L, "LAZDONAS_PAG", 142L, "Lazdonas pag." },
                    { 520L, "DZELZAVAS_PAG", 142L, "Dzelzavas pag." },
                    { 521L, "OSUPES_PAG", 142L, "Ošupes pag." },
                    { 522L, "ARONAS_PAG", 142L, "Aronas pag." },
                    { 523L, "BARKAVA", 142L, "Barkava" },
                    { 524L, "SIDGUNDA", 144L, "Sidgunda" },
                    { 525L, "BUKAS", 144L, "Bukas" },
                    { 526L, "VITE", 144L, "Vite" },
                    { 527L, "MALPILS", 144L, "Mālpils" },
                    { 565L, "PRIEKULE", 164L, "Priekule" },
                    { 528L, "UPMALAS", 144L, "Upmalas" },
                    { 530L, "SKULTE", 146L, "Skulte" },
                    { 531L, "VETRAS", 146L, "Vētras" },
                    { 532L, "JAUNMARUPE", 146L, "Jaunmārupe" },
                    { 533L, "TIRAINE", 146L, "Tīraine" },
                    { 534L, "LIDOSTA_RIGA", 146L, "Lidosta \"Rīga\"" },
                    { 535L, "MAZSALACA", 148L, "Mazsalaca" },
                    { 536L, "RAMATAS_PAG", 148L, "Ramatas pag." },
                    { 537L, "MAZSALACAS_PAG", 148L, "Mazsalacas pag." },
                    { 538L, "SKANKALNES_PAG", 148L, "Skaņkalnes pag." },
                    { 539L, "SELU_PAG", 148L, "Sēļu pag." },
                    { 529L, "MARUPE", 146L, "Mārupe" },
                    { 566L, "VIRGAS_PAG", 164L, "Virgas pag." },
                    { 567L, "KALETU_PAG", 164L, "Kalētu pag." },
                    { 568L, "PRIEKULES_PAG", 164L, "Priekules pag." },
                    { 595L, "LENDZU_PAG", 168L, "Lendžu pag." },
                    { 596L, "BERZGALES_PAG", 168L, "Bērzgales pag." },
                    { 597L, "SILMALAS_PAG", 168L, "Silmalas pag." },
                    { 598L, "VEREMU_PAG", 168L, "Vērēmu pag." },
                    { 599L, "KANTINIEKU_PAG", 168L, "Kantinieku pag." },
                    { 600L, "ILZESKALNA_PAG", 168L, "Ilzeskalna pag." },
                    { 601L, "MALTA", 168L, "Malta" },
                    { 602L, "RUCAVAS_PAG", 170L, "Rucavas pag." },
                    { 603L, "DUNIKAS_PAG", 170L, "Dunikas pag." },
                    { 604L, "JECI", 170L, "Ječi" },
                    { 594L, "NAUTRENU_PAG", 168L, "Nautrēnu pag." },
                    { 605L, "RUGAJU_PAG", 172L, "Rugāju pag." },
                    { 607L, "SVITENES_PAG", 174L, "Svitenes pag." },
                    { 608L, "RUNDALES_PAG", 174L, "Rundāles pag." },
                    { 609L, "VIESTURU_PAG", 174L, "Viesturu pag." },
                    { 610L, "RUJIENA", 176L, "Rūjiena" },
                    { 611L, "IPIKU_PAG", 176L, "Ipiķu pag." },
                    { 612L, "VILPULKAS_PAG", 176L, "Vilpulkas pag." },
                    { 613L, "LODES_PAG", 176L, "Lodes pag." },
                    { 614L, "JERU_PAG", 176L, "Jeru pag." },
                    { 615L, "AINAZI", 178L, "Ainaži" },
                    { 616L, "SALACGRIVA", 178L, "Salacgrīva" },
                    { 606L, "LAZDUKALNA_PAG", 172L, "Lazdukalna pag." },
                    { 517L, "MARCIENAS_PAG", 142L, "Mārcienas pag." },
                    { 593L, "MALTAS_PAG", 168L, "Maltas pag." },
                    { 591L, "MAKONKALNA_PAG", 168L, "Mākoņkalna pag." },
                    { 569L, "BUNKAS_PAG", 164L, "Bunkas pag." },
                    { 570L, "GRAMZDAS_PAG", 164L, "Gramzdas pag." },
                    { 571L, "LIEPAS_PAG", 166L, "Liepas pag." },
                    { 572L, "VESELAVAS_PAG", 166L, "Veselavas pag." },
                    { 573L, "PRIEKULU_PAG", 166L, "Priekuļu pag." },
                    { 574L, "MARSNENU_PAG", 166L, "Mārsnēnu pag." },
                    { 575L, "PRIEKUĻI", 166L, "Priekuļi" },
                    { 576L, "GAIGALAVAS_PAG", 168L, "Gaigalavas pag." },
                    { 577L, "OZOLMUIZAS_PAG", 168L, "Ozolmuižas pag." },
                    { 578L, "RIKAVAS_PAG", 168L, "Rikavas pag." },
                    { 592L, "STRUZANU_PAG", 168L, "Stružānu pag." },
                    { 579L, "AUDRINU_PAG", 168L, "Audriņu pag." },
                    { 581L, "FEIMANU_PAG", 168L, "Feimaņu pag." },
                    { 582L, "DRICANU_PAG", 168L, "Dricānu pag." },
                    { 583L, "PUSAS_PAG", 168L, "Pušas pag." },
                    { 584L, "CORNAJAS_PAG", 168L, "Čornajas pag." },
                    { 585L, "GRISKANU_PAG", 168L, "Griškānu pag." },
                    { 586L, "KAUNATAS_PAG", 168L, "Kaunatas pag." },
                    { 587L, "NAGLU_PAG", 168L, "Nagļu pag." },
                    { 588L, "SAKSTAGALA_PAG", 168L, "Sakstagala pag." },
                    { 589L, "STOLEROVAS_PAG", 168L, "Stoļerovas pag." },
                    { 590L, "LUZNAVAS_PAG", 168L, "Lūznavas pag." },
                    { 580L, "OZOLAINES_PAG", 168L, "Ozolaines pag." },
                    { 617L, "LIEPUPES_PAG", 178L, "Liepupes pag." },
                    { 516L, "METRIENAS_PAG", 142L, "Mētrienas pag." },
                    { 514L, "SARKANU_PAG", 142L, "Sarkaņu pag." },
                    { 441L, "VIRCAVAS_PAG", 122L, "Vircavas pag." },
                    { 442L, "ELEJA", 122L, "Eleja" },
                    { 443L, "ATPUTA", 122L, "Atpūta" },
                    { 444L, "TUSKI", 122L, "Tušķi" },
                    { 445L, "VITOLINI", 122L, "Vītoliņi" },
                    { 446L, "KARSAVA", 124L, "Kārsava" },
                    { 447L, "MERDZENES_PAG", 124L, "Mērdzenes pag." },
                    { 448L, "SALNAVAS_PAG", 124L, "Salnavas pag." },
                    { 449L, "MEZVIDU_PAG", 124L, "Mežvidu pag." },
                    { 450L, "MALNAVAS_PAG", 124L, "Malnavas pag." },
                    { 451L, "GOLISEVAS_PAG", 124L, "Goliševas pag." },
                    { 452L, "BEBRU_PAG", 126L, "Bebru pag." },
                    { 453L, "IRSU_PAG", 126L, "Iršu pag." },
                    { 454L, "KOKNESES_PAG", 126L, "Kokneses pag." },
                    { 455L, "KOKNESE", 126L, "Koknese" },
                    { 456L, "KRIMULDAS_PAG", 128L, "Krimuldas pag." },
                    { 457L, "LEDURGAS_PAG", 128L, "Lēdurgas pag." },
                    { 458L, "VIPES_PAG", 130L, "Vīpes pag." },
                    { 459L, "KUKU_PAG", 130L, "Kūku pag." },
                    { 460L, "VARIESU_PAG", 130L, "Variešu pag." },
                    { 461L, "MEZARES_PAG", 130L, "Mežāres pag." },
                    { 440L, "ZALENIEKU_PAG", 122L, "Zaļenieku pag." },
                    { 439L, "ELEJAS_PAG", 122L, "Elejas pag." },
                    { 438L, "VILCES_PAG", 122L, "Vilces pag." },
                    { 437L, "PLATONES_PAG", 122L, "Platones pag." },
                    { 415L, "SERENES_PAG", 116L, "Sērenes pag." },
                    { 416L, "DAUDZESES_PAG", 116L, "Daudzeses pag." },
                    { 417L, "SUNAKSTES_PAG", 116L, "Sunākstes pag." },
                    { 418L, "SECES_PAG", 116L, "Seces pag." },
                    { 419L, "STABURAGA_PAG", 116L, "Staburaga pag." },
                    { 420L, "JAUNPILS_PAG", 118L, "Jaunpils pag." },
                    { 421L, "VIESATU_PAG", 118L, "Viesatu pag." },
                    { 422L, "LEIMANU_PAG", 120L, "Leimaņu pag." },
                    { 423L, "RUBENES_PAG", 120L, "Rubenes pag." },
                    { 424L, "DIGNAJAS_PAG", 120L, "Dignājas pag." },
                    { 462L, "KRUSTPILS_PAG", 130L, "Krustpils pag." },
                    { 425L, "KALNA_PAG", 120L, "Kalna pag." },
                    { 427L, "ABELU_PAG", 120L, "Ābeļu pag." },
                    { 428L, "DUNAVAS_PAG", 120L, "Dunavas pag." },
                    { 429L, "GLUDAS_PAG", 122L, "Glūdas pag." },
                    { 430L, "LIVBERZES_PAG", 122L, "Līvbērzes pag." },
                    { 431L, "SESAVAS_PAG", 122L, "Sesavas pag." },
                    { 432L, "VALGUNDES_PAG", 122L, "Valgundes pag." },
                    { 433L, "JAUNSVIRLAUKAS_PAG", 122L, "Jaunsvirlaukas pag." },
                    { 434L, "SVETES_PAG", 122L, "Svētes pag." },
                    { 435L, "KALNCIEMA_PAG", 122L, "Kalnciema pag." },
                    { 436L, "LIELPLATONES_PAG", 122L, "Lielplatones pag." },
                    { 426L, "ZASAS_PAG", 120L, "Zasas pag." },
                    { 463L, "ATASIENES_PAG", 130L, "Atašienes pag." },
                    { 464L, "KULDIGA", 132L, "Kuldīga" },
                    { 465L, "RUMBAS_PAG", 132L, "Rumbas pag." },
                    { 492L, "UMURGAS_PAG", 138L, "Umurgas pag." },
                    { 493L, "SKULTES_PAG", 138L, "Skultes pag." },
                    { 494L, "PALES_PAG", 138L, "Pāles pag." },
                    { 495L, "VILKENES_PAG", 138L, "Viļķenes pag." },
                    { 496L, "ZIEMELBLAZMA", 138L, "Ziemeļblāzma" },
                    { 497L, "SKULTE_LIMBAZU", 138L, "Skulte" },
                    { 498L, "LUDZA", 140L, "Ludza" },
                    { 499L, "ISNAUDAS_PAG", 140L, "Isnaudas pag." },
                    { 500L, "PILDAS_PAG", 140L, "Pildas pag." },
                    { 501L, "NUKSU_PAG", 140L, "Ņukšu pag." },
                    { 491L, "KATVARU_PAG", 138L, "Katvaru pag." },
                    { 502L, "BRIGU_PAG", 140L, "Briģu pag." },
                    { 504L, "ISTRAS_PAG", 140L, "Istras pag." },
                    { 505L, "CIRMAS_PAG", 140L, "Cirmas pag." },
                    { 506L, "RUNDENU_PAG", 140L, "Rundēnu pag." },
                    { 507L, "PURENU_PAG", 140L, "Pureņu pag." },
                    { 508L, "MADONA", 142L, "Madona" },
                    { 509L, "BARKAVAS_PAG", 142L, "Barkavas pag." },
                    { 510L, "BERZAUNES_PAG", 142L, "Bērzaunes pag." },
                    { 511L, "LAUDONAS_PAG", 142L, "Ļaudonas pag." },
                    { 512L, "VESTIENAS_PAG", 142L, "Vestienas pag." },
                    { 513L, "LIEZERES_PAG", 142L, "Liezēres pag." },
                    { 503L, "NIRZAS_PAG", 140L, "Nirzas pag." },
                    { 515L, "KALSNAVAS_PAG", 142L, "Kalsnavas pag." },
                    { 490L, "VIDRIZU_PAG", 138L, "Vidrižu pag." },
                    { 488L, "LIMBAZI", 138L, "Limbaži" },
                    { 466L, "SNEPELES_PAG", 132L, "Snēpeles pag." },
                    { 467L, "GUDENIEKU_PAG", 132L, "Gudenieku pag." },
                    { 468L, "EDOLES_PAG", 132L, "Ēdoles pag." },
                    { 469L, "LAIDU_PAG", 132L, "Laidu pag." },
                    { 470L, "PELCU_PAG", 132L, "Pelču pag." },
                    { 471L, "PADURES_PAG", 132L, "Padures pag." },
                    { 472L, "KURMALES_PAG", 132L, "Kurmāles pag." },
                    { 473L, "VARMES_PAG", 132L, "Vārmes pag." },
                    { 474L, "KABILES_PAG", 132L, "Kabiles pag." },
                    { 475L, "IVANDES_PAG", 132L, "Īvandes pag." },
                    { 489L, "LIMBAZU_PAG", 138L, "Limbažu pag." },
                    { 476L, "RENDAS_PAG", 132L, "Rendas pag." },
                    { 478L, "BALOZI", 134L, "Baloži" },
                    { 479L, "VALDLAUCI", 134L, "Valdlauči" },
                    { 480L, "KEKAVAS_PAG", 134L, "Ķekavas pag." },
                    { 481L, "DAUGMALES_PAG", 134L, "Daugmales pag." },
                    { 482L, "KEKAVA", 134L, "Ķekava" },
                    { 483L, "RAMAVA", 134L, "Rāmava" },
                    { 484L, "KROGSILS", 134L, "Krogsils" },
                    { 485L, "ODUKALNS", 134L, "Odukalns" },
                    { 486L, "LIGATNE", 136L, "Līgatne" },
                    { 487L, "LIGATNES_PAG", 136L, "Līgatnes pag." },
                    { 477L, "TURLAVAS_PAG", 132L, "Turlavas pag." },
                    { 414L, "JAUNJELGAVAS_PAG", 116L, "Jaunjelgavas pag." },
                    { 618L, "AINAZU_PAG", 178L, "Ainažu pag." },
                    { 620L, "TUJA", 178L, "Tūja" },
                    { 750L, "SOKOLKU_PAG", 214L, "Sokolku pag." },
                    { 751L, "DEKSARES_PAG", 214L, "Dekšāres pag." },
                    { 752L, "VILANU_PAG", 214L, "Viļānu pag." },
                    { 753L, "VECATES_PAG", 216L, "Vecates pag." },
                    { 754L, "BURTNIEKU_PAG", 216L, "Burtnieku pag." },
                    { 755L, "RENCENU_PAG", 216L, "Rencēnu pag." },
                    { 756L, "VALMIERAS_PAG", 216L, "Valmieras pag." },
                    { 757L, "EVELES_PAG", 216L, "Ēveles pag." },
                    { 758L, "MATISU_PAG", 216L, "Matīšu pag." },
                    { 759L, "VALMIERMUIŽA", 216L, "Valmiermuiža" },
                    { 760L, "JUMURDAS_PAG", 218L, "Jumurdas pag." },
                    { 761L, "SAUSNEJAS_PAG", 218L, "Sausnējas pag." },
                    { 762L, "ERGLU_PAG", 218L, "Ērgļu pag." },
                    { 763L, "ERGLI", 218L, "Ērgļi" },
                    { 764L, "PABAZI", 220L, "Pabaži" },
                    { 765L, "ABELITE", 220L, "Ābelīte" },
                    { 766L, "VAIVARINI", 220L, "Vaivariņi" },
                    { 767L, "GARSMUIZA", 220L, "Gāršmuiža" },
                    { 768L, "JAUNKRIMULDA", 220L, "Jaunkrimulda" },
                    { 769L, "SEJA", 220L, "Sēja" },
                    { 770L, "MURJANI", 220L, "Murjāņi" },
                    { 749L, "VILANI", 214L, "Viļāni" },
                    { 748L, "SKILBENU_PAG", 212L, "Šķilbēnu pag." },
                    { 747L, "MEDNEVAS_PAG", 212L, "Medņevas pag." },
                    { 746L, "ZIGURU_PAG", 212L, "Žīguru pag." },
                    { 724L, "PILTENE", 208L, "Piltene" },
                    { 725L, "PUZES_PAG", 208L, "Puzes pag." },
                    { 726L, "PILTENES_PAG", 208L, "Piltenes pag." },
                    { 727L, "USMAS_PAG", 208L, "Usmas pag." },
                    { 728L, "ZIRU_PAG", 208L, "Ziru pag." },
                    { 729L, "ANCES_PAG", 208L, "Ances pag." },
                    { 730L, "JURKALNES_PAG", 208L, "Jūrkalnes pag." },
                    { 731L, "UZAVAS_PAG", 208L, "Užavas pag." },
                    { 732L, "UGALES_PAG", 208L, "Ugāles pag." },
                    { 733L, "POPES_PAG", 208L, "Popes pag." },
                    { 771L, "LOJA", 220L, "Loja" },
                    { 734L, "ZLEKU_PAG", 208L, "Zlēku pag." },
                    { 736L, "VARVES_PAG", 208L, "Vārves pag." },
                    { 737L, "VIESITE", 210L, "Viesīte" },
                    { 738L, "SAUKAS_PAG", 210L, "Saukas pag." },
                    { 739L, "RITES_PAG", 210L, "Rites pag." },
                    { 740L, "VIESITES_PAG", 210L, "Viesītes pag." },
                    { 741L, "ELKSNU_PAG", 210L, "Elkšņu pag." },
                    { 742L, "VILAKA", 212L, "Viļaka" },
                    { 743L, "KUPRAVAS_PAG", 212L, "Kupravas pag." },
                    { 744L, "VECUMU_PAG", 212L, "Vecumu pag." },
                    { 745L, "SUSAJU_PAG", 212L, "Susāju pag." },
                    { 735L, "TARGALES_PAG", 208L, "Tārgales pag." },
                    { 772L, "VANGAZI", 222L, "Vangaži" },
                    { 773L, "INCUKALNA_PAG", 222L, "Inčukalna pag." },
                    { 774L, "INCUKALNS", 222L, "Inčukalns" },
                    { 801L, "PODKAJAS", 232L, "Podkājas" },
                    { 802L, "MUCENIEKI", 232L, "Mucenieki" },
                    { 803L, "ROTKALI", 232L, "Rotkaļi" },
                    { 804L, "JAUNBAGUMI", 232L, "Jaunbagumi" },
                    { 805L, "JAUNMUCENIEKI", 232L, "Jaunmucenieki" },
                    { 806L, "KANGARI", 232L, "Kangari" },
                    { 807L, "BAJARKROGS", 232L, "Bajārkrogs" },
                    { 808L, "SILAJANU_PAG", 234L, "Silajāņu pag." },
                    { 809L, "GALENU_PAG", 234L, "Galēnu pag." },
                    { 810L, "SILUKALNA_PAG", 234L, "Sīļukalna pag." },
                    { 800L, "NAGELMUIZA", 232L, "Nāgelmuiža" },
                    { 811L, "STABULNIEKU_PAG", 234L, "Stabulnieku pag." },
                    { 813L, "RUSONAS_PAG", 234L, "Rušonas pag." },
                    { 814L, "ULBROKA", 236L, "Ulbroka" },
                    { 815L, "LICI", 236L, "Līči" },
                    { 816L, "SAULISU_CIEMS", 236L, "Saulīšu ciems" },
                    { 817L, "SAURIESI", 236L, "Saurieši" },
                    { 818L, "CEKULE", 236L, "Cekule" },
                    { 819L, "UPESLEJAS", 236L, "Upeslejas" },
                    { 820L, "VALODZES", 236L, "Vālodzes" },
                    { 821L, "DZIDRINAS", 236L, "Dzidriņas" },
                    { 822L, "STOPINU_PAG", 236L, "Stopiņu pag." },
                    { 812L, "RIEBINU_PAG", 234L, "Riebiņu pag." },
                    { 723L, "VECUMNIEKI", 206L, "Vecumnieki" },
                    { 799L, "ULUPJI", 232L, "Ūlupji" },
                    { 797L, "KAKCIEMS", 232L, "Kākciems" },
                    { 775L, "EGLUPE", 222L, "Egļupe" },
                    { 776L, "JAUNPIEBALGAS_PAG", 224L, "Jaunpiebalgas pag." },
                    { 777L, "ZOSENU_PAG", 224L, "Zosēnu pag." },
                    { 778L, "SAULKRASTI", 226L, "Saulkrasti" },
                    { 779L, "SAULKRASTU_PAG", 226L, "Saulkrastu pag." },
                    { 780L, "ZVEJNIEKCIEMS", 226L, "Zvejniekciems" },
                    { 781L, "DRUSTU_PAG", 228L, "Drustu pag." },
                    { 782L, "RAUNAS_PAG", 228L, "Raunas pag." },
                    { 783L, "RAUNA", 228L, "Rauna" },
                    { 784L, "LIELVARDE", 230L, "Lielvārde" },
                    { 798L, "GAIDAS", 232L, "Gaidas" },
                    { 785L, "JUMPRAVAS_PAG", 230L, "Jumpravas pag." },
                    { 787L, "LEDMANES_PAG", 230L, "Lēdmanes pag." },
                    { 788L, "ROPAZI", 232L, "Ropaži" },
                    { 789L, "ZAKUMUIZA", 232L, "Zaķumuiža" },
                    { 790L, "LIELKANGARI", 232L, "Lielkangari" },
                    { 791L, "SILAKROGS", 232L, "Silakrogs" },
                    { 792L, "TUMSUPE", 232L, "Tumšupe" },
                    { 793L, "AUGSCIEMS", 232L, "Augšciems" },
                    { 794L, "BAJARI", 232L, "Bajāri" },
                    { 795L, "VAVERKROGS", 232L, "Vāverkrogs" },
                    { 796L, "VILLASMUIZA", 232L, "Villasmuiža" },
                    { 786L, "LIELVARDES_PAG", 230L, "Lielvārdes pag." },
                    { 619L, "SALACGRIVAS_PAG", 178L, "Salacgrīvas pag." },
                    { 722L, "SKAISTKALNE", 206L, "Skaistkalne" },
                    { 720L, "VECUMNIEKU_PAG", 206L, "Vecumnieku pag." },
                    { 647L, "NIKRACES_PAG", 186L, "Nīkrāces pag." },
                    { 648L, "RUDBARZU_PAG", 186L, "Rudbāržu pag." },
                    { 649L, "SKRUNDAS_PAG", 186L, "Skrundas pag." },
                    { 650L, "SMILTENE", 188L, "Smiltene" },
                    { 651L, "BLOMES_PAG", 188L, "Blomes pag." },
                    { 652L, "PALSMANES_PAG", 188L, "Palsmanes pag." },
                    { 653L, "BILSKAS_PAG", 188L, "Bilskas pag." },
                    { 654L, "LAUNKALNES_PAG", 188L, "Launkalnes pag." },
                    { 655L, "SMILTENES_PAG", 188L, "Smiltenes pag." },
                    { 656L, "VARINU_PAG", 188L, "Variņu pag." },
                    { 657L, "GRUNDZALES_PAG", 188L, "Grundzāles pag." },
                    { 658L, "BRANTU_PAG", 188L, "Brantu pag." },
                    { 659L, "SEDA", 190L, "Seda" },
                    { 660L, "STENCI", 190L, "Strenči" },
                    { 661L, "PLANU_PAG", 190L, "Plāņu pag." },
                    { 662L, "JERCENU_PAG", 190L, "Jērcēnu pag." },
                    { 663L, "STENDE", 192L, "Stende" },
                    { 664L, "SABILE", 192L, "Sabile" },
                    { 665L, "TALSI", 192L, "Talsi" },
                    { 666L, "VALDEMARPILS", 192L, "Valdemārpils" },
                    { 667L, "LAIDZES_PAG", 192L, "Laidzes pag." },
                    { 646L, "RANKU_PAG", 186L, "Raņķu pag." },
                    { 645L, "SKRUNDA", 186L, "Skrunda" },
                    { 644L, "LICI", 184L, "Līči" },
                    { 643L, "KLIDZINA", 184L, "Klidziņa" },
                    { 621L, "LANI", 178L, "Lāņi" },
                    { 622L, "SELPILS_PAG", 180L, "Sēlpils pag." },
                    { 623L, "SALAS_SALAS", 180L, "Salas pag." },
                    { 624L, "SALDUS", 182L, "Saldus" },
                    { 625L, "RUBAS_PAG", 182L, "Rubas pag." },
                    { 626L, "SKEDES_PAG", 182L, "Šķēdes pag." },
                    { 627L, "JAUNAUCES_PAG", 182L, "Jaunauces pag." },
                    { 628L, "NIGRANDES_PAG", 182L, "Nīgrandes pag." },
                    { 629L, "ZANAS_PAG", 182L, "Zaņas pag." },
                    { 630L, "ZIRNU_PAG", 182L, "Zirņu pag." },
                    { 668L, "VALDGALES_PAG", 192L, "Valdgales pag." },
                    { 631L, "JAUNLUTRINU_PAG", 182L, "Jaunlutriņu pag." },
                    { 633L, "VADAKSTES_PAG", 182L, "Vadakstes pag." },
                    { 634L, "ZVARDES_PAG", 182L, "Zvārdes pag." },
                    { 635L, "KURSISU_PAG", 182L, "Kursīšu pag." },
                    { 636L, "SALDUS_PAG", 182L, "Saldus pag." },
                    { 637L, "EZERES_PAG", 182L, "Ezeres pag." },
                    { 638L, "NOVADNIEKU_PAG", 182L, "Novadnieku pag." },
                    { 639L, "LUTRINU_PAG", 182L, "Lutriņu pag." },
                    { 640L, "SKRIVERI", 184L, "Skrīveri" },
                    { 641L, "ZIEDUGRAVAS", 184L, "Ziedugravas" },
                    { 642L, "ZEMKOPIBAS_INSTITUTS", 184L, "Zemkopības institūts" },
                    { 632L, "PAMPALU_PAG", 182L, "Pampāļu pag." },
                    { 669L, "ARLAVAS_PAG", 192L, "Ārlavas pag." },
                    { 670L, "GIBULU_PAG", 192L, "Ģibuļu pag." },
                    { 671L, "IVES_PAG", 192L, "Īves pag." },
                    { 698L, "VIJCIEMA_PAG", 198L, "Vijciema pag." },
                    { 699L, "ZVARTAVAS_PAG", 198L, "Zvārtavas pag." },
                    { 700L, "ERGEMES_PAG", 198L, "Ērģemes pag." },
                    { 701L, "DIKLU_PAG", 200L, "Dikļu pag." },
                    { 702L, "KOCENU_PAG", 200L, "Kocēnu pag." },
                    { 703L, "ZILAKALNA_PAG", 200L, "Zilākalna pag." },
                    { 704L, "BERZAINES_PAG", 200L, "Bērzaines pag." },
                    { 705L, "VAIDAVAS_PAG", 200L, "Vaidavas pag." },
                    { 706L, "KOCENI", 200L, "Kocēni" },
                    { 707L, "VARAKLANI", 202L, "Varakļāni" },
                    { 697L, "VALKAS_PAG", 198L, "Valkas pag." },
                    { 708L, "VARAKLANU_PAG", 202L, "Varakļānu pag." },
                    { 710L, "INESU_PAG", 204L, "Inešu pag." },
                    { 711L, "TAURENES_PAG", 204L, "Taurenes pag." },
                    { 712L, "DZERBENES_PAG", 204L, "Dzērbenes pag." },
                    { 713L, "KAIVES_PAG", 204L, "Kaives pag." },
                    { 714L, "VECPIEBALGAS_PAG", 204L, "Vecpiebalgas pag." },
                    { 715L, "VECPIEBALGA", 204L, "Vecpiebalga" },
                    { 716L, "STELPES_PAG", 206L, "Stelpes pag." },
                    { 717L, "BARBELES_PAG", 206L, "Bārbeles pag." },
                    { 718L, "KURMENES_PAG", 206L, "Kurmenes pag." },
                    { 719L, "SKAISTKALNES_PAG", 206L, "Skaistkalnes pag." },
                    { 709L, "MURMASTIENES_PAG", 202L, "Murmastienes pag." },
                    { 721L, "VALLES_PAG", 206L, "Valles pag." },
                    { 696L, "KARKU_PAG", 198L, "Kārķu pag." },
                    { 694L, "VAINODE", 196L, "Vaiņode" },
                    { 672L, "LUBES_PAG", 192L, "Lubes pag." },
                    { 673L, "STRAZDES_PAG", 192L, "Strazdes pag." },
                    { 674L, "VIRBU_PAG", 192L, "Virbu pag." },
                    { 675L, "BALGALES_PAG", 192L, "Balgales pag." },
                    { 676L, "KULCIEMA_PAG", 192L, "Ķūļciema pag." },
                    { 677L, "LIBAGU_PAG", 192L, "Lībagu pag." },
                    { 678L, "LAUCIENAS_PAG", 192L, "Laucienes pag." },
                    { 679L, "VANDZENES_PAG", 192L, "Vandzenes pag." },
                    { 680L, "ABAVAS_PAG", 192L, "Abavas pag." },
                    { 681L, "TUKUMS", 194L, "Tukums" },
                    { 695L, "VALKA", 198L, "Valka" },
                    { 682L, "DZUKSTES_PAG", 194L, "Džūkstes pag." },
                    { 684L, "LESTENES_PAG", 194L, "Lestenes pag." },
                    { 685L, "SEMES_PAG", 194L, "Sēmes pag." },
                    { 686L, "TUMES_PAG", 194L, "Tumes pag." },
                    { 687L, "SLAMPES_PAG", 194L, "Slampes pag." },
                    { 688L, "IRLAVAS_PAG", 194L, "Irlavas pag." },
                    { 689L, "PURES_PAG", 194L, "Pūres pag." },
                    { 690L, "DEGOLES_PAG", 194L, "Degoles pag." },
                    { 691L, "ZENTENES_PAG", 194L, "Zentenes pag." },
                    { 692L, "EMBUTES_PAG", 196L, "Embūtes pag." },
                    { 693L, "VAINODES_PAG", 196L, "Vaiņodes pag." },
                    { 683L, "JAUNSATU_PAG", 194L, "Jaunsātu pag." },
                    { 413L, "JAUNJELGAVA", 116L, "Jaunjelgava" },
                    { 412L, "LEJASCIEMA_PAG", 114L, "Lejasciema pag." },
                    { 411L, "BELAVAS_PAG", 114L, "Beļavas pag." },
                    { 131L, "TURKU_PAG", 36L, "Turku pag." },
                    { 132L, "JERSIKAS_PAG", 36L, "Jersikas pag." },
                    { 133L, "KEGUMS", 38L, "Ķegums" },
                    { 134L, "TOMES_PAG", 38L, "Tomes pag." },
                    { 135L, "BIRZGALES_PAG", 38L, "Birzgales pag." },
                    { 136L, "REMBATES_PAG", 38L, "Rembates pag." },
                    { 137L, "MISA", 40L, "Misa" },
                    { 138L, "DZIMTMISA", 40L, "Dzimtmisa" },
                    { 139L, "DIMZUKALNS", 40L, "Dimzukalns" },
                    { 140L, "ZALITE", 40L, "Zālīte" },
                    { 141L, "DZELZAMURS", 40L, "Dzelzāmurs" },
                    { 142L, "ROSME", 40L, "Rosme" },
                    { 143L, "IECAVA", 40L, "Iecava" },
                    { 144L, "ZORGI", 40L, "Zorģi" },
                    { 145L, "AUDRUPI", 40L, "Audrupi" },
                    { 146L, "OGRE", 42L, "Ogre" },
                    { 147L, "KEIPENES_PAG", 42L, "Ķeipenes pag." },
                    { 148L, "OGRESGALA_PAG", 42L, "Ogresgala pag." },
                    { 149L, "TAURUPES_PAG", 42L, "Taurupes pag." },
                    { 150L, "MADLIENAS_PAG", 42L, "Madlienas pag." },
                    { 151L, "KRAPES_PAG", 42L, "Krapes pag." },
                    { 130L, "RUDZATU_PAG", 36L, "Rudzātu pag." },
                    { 129L, "SUTRU_PAG", 36L, "Sutru pag." },
                    { 128L, "ROZUPES_PAG", 36L, "Rožupes pag." },
                    { 127L, "LIVANI", 36L, "Līvāni" },
                    { 105L, "KAPLAVAS_PAG", 26L, "Kaplavas pag." },
                    { 106L, "PIEDRUJAS_PAG", 26L, "Piedrujas pag." },
                    { 107L, "AULEJAS_PAG", 26L, "Aulejas pag." },
                    { 108L, "INDRA", 26L, "Indra" },
                    { 109L, "BROCENI", 28L, "Brocēni" },
                    { 110L, "REMTES_PAG", 28L, "Remtes pag." },
                    { 111L, "BLIDENES_PAG", 28L, "Blīdenes pag." },
                    { 112L, "GAIKU_PAG", 28L, "Gaiķu pag." },
                    { 113L, "CIECERES_PAG", 28L, "Cieceres pag." },
                    { 114L, "PREILI", 30L, "Preiļi" },
                    { 152L, "MAZOZOLU_PAG", 42L, "Mazozolu pag." },
                    { 115L, "AIZKALNES_PAG", 30L, "Aizkalnes pag." },
                    { 117L, "SAUNAS_PAG", 30L, "Saunas pag." },
                    { 118L, "PELECU_PAG", 30L, "Pelēču pag." },
                    { 119L, "DURBE", 32L, "Durbe" },
                    { 120L, "DURBES_PAG", 32L, "Durbes pag." },
                    { 121L, "VECPILS_PAG", 32L, "Vecpils pag." },
                    { 122L, "DUNALKAS_PAG", 32L, "Dunalkas pag." },
                    { 123L, "TADAIKU_PAG", 32L, "Tadaiķu pag." },
                    { 124L, "UPMALAS_PAG", 34L, "Upmalas pag." },
                    { 125L, "ROZKALNU_PAG", 34L, "Rožkalnu pag." },
                    { 126L, "VARKAVAS_PAG", 34L, "Vārkavas pag." },
                    { 116L, "PREILU_PAG", 30L, "Preiļu pag." },
                    { 153L, "SUNTAZU_PAG", 42L, "Suntažu pag." },
                    { 154L, "LAUBERES_PAG", 42L, "Lauberes pag." },
                    { 155L, "MENGELES_PAG", 42L, "Meņģeles pag." },
                    { 182L, "SUBATE", 54L, "Subate" },
                    { 183L, "EGLAINES_PAG", 54L, "Eglaines pag." },
                    { 184L, "BEBRENES_PAG", 54L, "Bebrenes pag." },
                    { 185L, "DVIETES_PAG", 54L, "Dvietes pag." },
                    { 186L, "PILSKALNES_PAG", 54L, "Pilskalnes pag." },
                    { 187L, "PRODES_PAG", 54L, "Prodes pag." },
                    { 188L, "SEDERES_PAG", 54L, "Šēderes pag." },
                    { 189L, "IKSKILE", 56L, "Ikšķile" },
                    { 190L, "TINUZU_PAG", 56L, "Tīnūžu pag." },
                    { 191L, "DAUGAVMALA", 56L, "Daugavmala" },
                    { 181L, "ILUKSTE", 54L, "Ilūkste" },
                    { 192L, "JAUNIKSKILE", 56L, "Jaunikšķile" },
                    { 194L, "KASTULINAS_PAG", 58L, "Kastuļinas pag." },
                    { 195L, "GRAVERU_PAG", 58L, "Grāveru pag." },
                    { 196L, "AGLONAS_PAG", 58L, "Aglonas pag." },
                    { 197L, "SKELTOVAS_PAG", 58L, "Šķeltovas pag." },
                    { 198L, "AGLONA", 58L, "Aglona" },
                    { 199L, "AIZPUTE", 60L, "Aizpute" },
                    { 200L, "CIRAVAS_PAG", 60L, "Cīravas pag." },
                    { 201L, "AIZPUTES_PAG", 60L, "Aizputes pag." },
                    { 202L, "KALVENES_PAG", 60L, "Kalvenes pag." },
                    { 203L, "LAZAS_PAG", 60L, "Lažas pag." },
                    { 193L, "ADAMLAUKS", 56L, "Ādamlauks" },
                    { 104L, "IZVALTAS_PAG", 26L, "Izvaltas pag." },
                    { 180L, "EGLUPE", 52L, "Egļupe" },
                    { 178L, "MORES_PAG", 52L, "Mores pag." },
                    { 156L, "OGRESGALS", 42L, "Ogresgals" },
                    { 157L, "TERVETES_PAG", 44L, "Tērvetes pag." },
                    { 158L, "BUKAISU_PAG", 44L, "Bukaišu pag." },
                    { 159L, "AUGSTKALNES_PAG", 44L, "Augstkalnes pag." },
                    { 160L, "ZILUPE", 46L, "Zilupe" },
                    { 161L, "PASIENES_PAG", 46L, "Pasienes pag." },
                    { 162L, "ZALESJES_PAG", 46L, "Zaļesjes pag." },
                    { 163L, "LAUDERU_PAG", 46L, "Lauderu pag." },
                    { 164L, "CENU_PAG", 48L, "Cenu pag." },
                    { 165L, "SALGALES_PAG", 48L, "Salgales pag." },
                    { 179L, "PELTES", 52L, "Peltes" },
                    { 166L, "OZOLNIEKU_PAG", 48L, "Ozolnieku pag." },
                    { 168L, "KANDAVA", 50L, "Kandava" },
                    { 169L, "VANES_PAG", 50L, "Vānes pag." },
                    { 170L, "ZEMITES_PAG", 50L, "Zemītes pag." },
                    { 171L, "ZANTES_PAG", 50L, "Zantes pag." },
                    { 172L, "MATKULES_PAG", 50L, "Matkules pag." },
                    { 173L, "KANDAVAS_PAG", 50L, "Kandavas pag." },
                    { 174L, "CERES_PAG", 50L, "Cēres pag." },
                    { 175L, "SIGULDA", 52L, "Sigulda" },
                    { 176L, "SIGULDAS_PAG", 52L, "Siguldas pag." },
                    { 177L, "ALLAZU_PAG", 52L, "Allažu pag." },
                    { 167L, "OZOLNIEKI", 48L, "Ozolnieki" },
                    { 204L, "KAZDANGAS_PAG", 60L, "Kazdangas pag." },
                    { 103L, "KALNIESU_PAG", 26L, "Kalniešu pag." },
                    { 101L, "ROBEZNIEKU_PAG", 26L, "Robežnieku pag." },
                    { 28L, "KLIVERSALA", 2L, "Klīversala" },
                    { 29L, "KRASTA_MASIVS", 2L, "Krasta masīvs" },
                    { 30L, "LUCAVSALA", 2L, "Lucavsala" },
                    { 31L, "MANGALU_PUSSALA", 2L, "Mangaļu pussala" },
                    { 32L, "MASKAVAS_PRIEKSPILSETA", 2L, "Maskavas priekšpilsēta" },
                    { 33L, "MEZAPARKS", 2L, "Mežaparks" },
                    { 34L, "MEZCIEMS", 2L, "Mežciems" },
                    { 35L, "MUKUSALA", 2L, "Mūkusala" }
                });

            migrationBuilder.InsertData(
                table: "City",
                columns: new[] { "Id", "Code", "CountyId", "Name" },
                values: new object[,]
                {
                    { 36L, "OZOLCIEMS", 2L, "Ozolciems" },
                    { 37L, "PARDAUGAVA", 2L, "Pārdaugava" },
                    { 38L, "PETERSALA", 2L, "Pētersala" },
                    { 39L, "PLESKODALE_SAMPETERIS", 2L, "Pleskodāle-Šampēteris" },
                    { 40L, "PURVCIEMS", 2L, "Purvciems" },
                    { 41L, "RUMBULA", 2L, "Rumbula" },
                    { 42L, "SARKANDAUGAVA", 2L, "Sarkandaugava" },
                    { 43L, "SKIROTAVA", 2L, "Šķirotava" },
                    { 44L, "SMERLIS", 2L, "Šmerlis" },
                    { 45L, "TEIKA", 2L, "Teika" },
                    { 46L, "TORNKALNS", 2L, "Torņakalns" },
                    { 47L, "VECAKI", 2L, "Vecāķi" },
                    { 48L, "VECDAUGAVA", 2L, "Vecdaugava" },
                    { 27L, "KLEISTI", 2L, "Kleisti" },
                    { 26L, "KIPSALA", 2L, "Ķīpsala" },
                    { 25L, "KENGARAGS", 2L, "Ķengarags" },
                    { 24L, "KATLAKALNS", 2L, "Katlakalns" },
                    { 2L, "APLOKCIEMS", 2L, "Aplokciems" },
                    { 3L, "BEBERBEKI", 2L, "Beberbeki" },
                    { 4L, "BERGI", 2L, "Berģi" },
                    { 5L, "BIERINI", 2L, "Bieriņi" },
                    { 6L, "BISUMUIZA", 2L, "Bišumuiža" },
                    { 7L, "BOLDERAJA", 2L, "Bolderāja" },
                    { 8L, "BUKULTI", 2L, "Bukulti" },
                    { 9L, "CENTRS", 2L, "Centrs" },
                    { 10L, "CENTRS", 2L, "Centrs" },
                    { 11L, "CENTRS", 2L, "Centrs" },
                    { 49L, "VECMILGRAVIS", 2L, "Vecmīlgrāvis" },
                    { 12L, "CIEKURKALNS", 2L, "Čiekurkalns" },
                    { 14L, "DARZINI", 2L, "Dārziņi" },
                    { 15L, "DAUGAVGRIVA", 2L, "Daugavgrīva" },
                    { 16L, "DREILINI", 2L, "Dreiliņi" },
                    { 17L, "DZIRCIEMS", 2L, "Dzirciems" },
                    { 18L, "GRIZINKALNS", 2L, "Grīziņkalns" },
                    { 19L, "ILGUCIEMS", 2L, "Iļģuciems" },
                    { 20L, "IMANTA", 2L, "Imanta" },
                    { 21L, "JAUNCIEMS", 2L, "Jaunciems" },
                    { 22L, "JAUNMILGRAVIS", 2L, "Jaunmīlgrāvis" },
                    { 23L, "JUGLA", 2L, "Jugla" },
                    { 13L, "DARZCIEMS", 2L, "Dārzciems" },
                    { 50L, "VECRIGA", 2L, "Vecrīga" },
                    { 51L, "ZAKUSALA", 2L, "Zaķusala" },
                    { 52L, "ZASULAUKS", 2L, "Zasulauks" },
                    { 79L, "DAUGAVPILS", 12L, "Daugavpils" },
                    { 80L, "REZEKNE", 14L, "Rēzekne" },
                    { 81L, "VALMIERA", 16L, "Valmiera" },
                    { 82L, "JEKABPILS", 18L, "Jēkabpils" },
                    { 83L, "ZVIRGZDENES_PAG", 20L, "Zvirgzdenes pag." },
                    { 84L, "BLONTU_PAG", 20L, "Blontu pag." },
                    { 85L, "LIDUMNIEKU_PAG", 20L, "Līdumnieku pag." },
                    { 86L, "CIBLAS_PAG", 20L, "Ciblas pag." },
                    { 87L, "PUSMUCOVAS_PAG", 20L, "Pušmucovas pag." },
                    { 88L, "DRABESU_PAG", 22L, "Drabešu pag." },
                    { 78L, "VALTERI", 10L, "Valteri" },
                    { 89L, "ZAUBES_PAG", 22L, "Zaubes pag." },
                    { 91L, "NITAURES_PAG", 22L, "Nītaures pag." },
                    { 92L, "AMATAS_PAG", 22L, "Amatas pag." },
                    { 93L, "LIVI", 22L, "Līvi" },
                    { 94L, "AIZKRAUKLE", 24L, "Aizkraukle" },
                    { 95L, "AIZKRAUKLES_PAG", 24L, "Aizkraukles pag." },
                    { 96L, "KRASLAVA", 26L, "Krāslava" },
                    { 97L, "KRASLAVAS_PAG", 26L, "Krāslavas pag." },
                    { 98L, "SKAISTAS_PAG", 26L, "Skaistas pag." },
                    { 99L, "UDRISU_PAG", 26L, "Ūdrīšu pag." },
                    { 100L, "KOMBULU_PAG", 26L, "Kombuļu pag." },
                    { 90L, "SKUJENES_PAG", 22L, "Skujenes pag." },
                    { 102L, "INDRAS_PAG", 26L, "Indras pag." },
                    { 77L, "VAIVARI", 10L, "Vaivari" },
                    { 75L, "PUMPURI", 10L, "Pumpuri" },
                    { 53L, "ZIEPNIEKKALNS", 2L, "Ziepniekkalns" },
                    { 54L, "ZOLITUDE", 2L, "Zolitūde" },
                    { 55L, "PLAVNIEKI", 2L, "Pļavnieki" },
                    { 56L, "JELGAVA", 4L, "Jelgava" },
                    { 57L, "LIEPAJA", 6L, "Liepāja" },
                    { 58L, "VENTSPILS", 8L, "Ventspils" },
                    { 59L, "JURMALA", 10L, "Jūrmala" },
                    { 60L, "ASARI", 10L, "Asari" },
                    { 61L, "BULDURI", 10L, "Bulduri" },
                    { 62L, "BULLUCIEMS", 10L, "Buļļuciems" },
                    { 76L, "SLOKA", 10L, "Sloka" },
                    { 63L, "DRUVCIEMS", 10L, "Druvciems" },
                    { 65L, "DZINTARI", 10L, "Dzintari" },
                    { 66L, "JAUNDUBULTI", 10L, "Jaundubulti" },
                    { 67L, "JAUNKEMERI", 10L, "Jaunķemeri" },
                    { 68L, "KAUGURCIEMS", 10L, "Kaugurciems" },
                    { 69L, "KAUGURI", 10L, "Kauguri" },
                    { 70L, "KEMERI", 10L, "Ķemeri" },
                    { 71L, "LIELUPE", 10L, "Lielupe" },
                    { 72L, "MAJORI", 10L, "Majori" },
                    { 73L, "MELLUZI", 10L, "Melluži" },
                    { 74L, "PRIEDAINE", 10L, "Priedaine" },
                    { 64L, "DUBULTI", 10L, "Dubulti" },
                    { 205L, "AKNISTE", 62L, "Aknīste" },
                    { 206L, "AKNISTES_PAG", 62L, "Aknīstes pag." },
                    { 207L, "GARSENES_PAG", 62L, "Gārsenes pag." },
                    { 338L, "VAIVES_PAG", 98L, "Vaives pag." },
                    { 339L, "CESVAINE", 100L, "Cesvaine" },
                    { 340L, "CESVAINES_PAG", 100L, "Cesvaines pag." },
                    { 341L, "DAGDA", 102L, "Dagda" },
                    { 342L, "ASUNES_PAG", 102L, "Asūnes pag." },
                    { 343L, "EZERNIEKU_PAG", 102L, "Ezernieku pag." },
                    { 344L, "KEPOVAS_PAG", 102L, "Ķepovas pag." },
                    { 345L, "SKAUNES_PAG", 102L, "Šķaunes pag." },
                    { 346L, "BERZINU_PAG", 102L, "Bērziņu pag." },
                    { 347L, "ANDRUPENES_PAG", 102L, "Andrupenes pag." },
                    { 348L, "KONSTANTINOVAS_PAG", 102L, "Konstantinovas pag." },
                    { 349L, "DAGDAS_PAG", 102L, "Dagdas pag." },
                    { 350L, "SVARINU_PAG", 102L, "Svariņu pag." },
                    { 351L, "ANDZELU_PAG", 102L, "Andzeļu pag." },
                    { 352L, "MEDUMU_PAG", 104L, "Medumu pag." },
                    { 353L, "VABOLES_PAG", 104L, "Vaboles pag." },
                    { 354L, "KALUPES_PAG", 104L, "Kalupes pag." },
                    { 355L, "DUBNAS_PAG", 104L, "Dubnas pag." },
                    { 356L, "LIKSNAS_PAG", 104L, "Līksnas pag." },
                    { 357L, "BIKERNIEKU_PAG", 104L, "Biķernieku pag." },
                    { 358L, "KALKUNES_PAG", 104L, "Kalkūnes pag." },
                    { 337L, "CESIS", 98L, "Cēsis" },
                    { 336L, "BRENGULU_PAG", 96L, "Brenguļu pag." },
                    { 335L, "KAUGURU_PAG", 96L, "Kauguru pag." },
                    { 334L, "TRIKATAS_PAG", 96L, "Trikātas pag." },
                    { 312L, "SPILVE", 88L, "Spilve" },
                    { 313L, "BALTINAVA", 90L, "Baltinava" },
                    { 314L, "BALVI", 92L, "Balvi" },
                    { 315L, "BERZPILS_PAG", 92L, "Bērzpils pag." },
                    { 316L, "LAZDULEJAS_PAG", 92L, "Lazdulejas pag." },
                    { 317L, "VIKSNAS_PAG", 92L, "Vīksnas pag." },
                    { 318L, "KUBULU_PAG", 92L, "Kubulu pag." },
                    { 319L, "KRISJANU_PAG", 92L, "Krišjāņu pag." },
                    { 320L, "BALVU_PAG", 92L, "Balvu pag." },
                    { 321L, "VECTILZAS_PAG", 92L, "Vectilžas pag." },
                    { 359L, "MALINOVAS_PAG", 104L, "Maļinovas pag." },
                    { 322L, "TILZAS_PAG", 92L, "Tilžas pag." },
                    { 324L, "BERZKALNES_PAG", 92L, "Bērzkalnes pag." },
                    { 325L, "BAUSKA", 94L, "Bauska" },
                    { 326L, "CERAUKSTES_PAG", 94L, "Ceraukstes pag." },
                    { 327L, "DAVINU_PAG", 94L, "Dāviņu pag." },
                    { 328L, "CODES_PAG", 94L, "Codes pag." },
                    { 329L, "ISLICES_PAG", 94L, "Īslīces pag." },
                    { 330L, "VECSAULES_PAG", 94L, "Vecsaules pag." },
                    { 331L, "GAILISU_PAG", 94L, "Gailīšu pag." },
                    { 332L, "BRUNAVAS_PAG", 94L, "Brunavas pag." },
                    { 333L, "MEZOTNES_PAG", 94L, "Mežotnes pag." },
                    { 323L, "BRIEZUCIEMA_PAG", 92L, "Briežuciema pag." },
                    { 360L, "LAUCESAS_PAG", 104L, "Laucesas pag." },
                    { 361L, "NICGALES_PAG", 104L, "Nīcgales pag." },
                    { 362L, "DEMENES_PAG", 104L, "Demenes pag." },
                    { 389L, "ENGURE", 110L, "Engure" },
                    { 390L, "LAPMEZCIEMS", 110L, "Lapmežciems" },
                    { 391L, "RAGACIEMS", 110L, "Ragaciems" },
                    { 392L, "SMARDE", 110L, "Smārde" },
                    { 393L, "GROBINA", 112L, "Grobiņa" },
                    { 394L, "BARTAS_PAG", 112L, "Bārtas pag." },
                    { 395L, "GROBINAS_PAG", 112L, "Grobiņas pag." },
                    { 396L, "GAVIEZES_PAG", 112L, "Gaviezes pag." },
                    { 397L, "MEDZES_PAG", 112L, "Medzes pag." },
                    { 398L, "SKEDE", 112L, "Šķēde" },
                    { 388L, "PLIENCIEMS", 110L, "Plieņciems" },
                    { 399L, "GULBENE", 114L, "Gulbene" },
                    { 401L, "DRUVIENAS_PAG", 114L, "Druvienas pag." },
                    { 402L, "STAMERIENAS_PAG", 114L, "Stāmerienas pag." },
                    { 403L, "LITENES_PAG", 114L, "Litenes pag." },
                    { 404L, "LIZUMA_PAG", 114L, "Lizuma pag." },
                    { 405L, "JAUNGULBENES_PAG", 114L, "Jaungulbenes pag." },
                    { 406L, "STRADU_PAG", 114L, "Stradu pag." },
                    { 407L, "GALGAUSKAS_PAG", 114L, "Galgauskas pag." },
                    { 408L, "DAUKSTU_PAG", 114L, "Daukstu pag." },
                    { 409L, "TIRZAS_PAG", 114L, "Tirzas pag." },
                    { 410L, "LIGO_PAG", 114L, "Līgo pag." },
                    { 400L, "RANKAS_PAG", 114L, "Rankas pag." },
                    { 311L, "MEZARES", 88L, "Mežāres" },
                    { 387L, "SMARDES_PAG", 110L, "Smārdes pag." },
                    { 385L, "ENGURES_PAG", 110L, "Engures pag." },
                    { 363L, "NAUJENES_PAG", 104L, "Naujenes pag." },
                    { 364L, "SVENTES_PAG", 104L, "Sventes pag." },
                    { 365L, "TABORES_PAG", 104L, "Tabores pag." },
                    { 366L, "AMBELU_PAG", 104L, "Ambeļu pag." },
                    { 367L, "VISKU_PAG", 104L, "Višķu pag." },
                    { 368L, "SKRUDALIENAS_PAG", 104L, "Skrudalienas pag." },
                    { 369L, "SALIENAS_PAG", 104L, "Salienas pag." },
                    { 370L, "VECSALIENAS_PAG", 104L, "Vecsalienas pag." },
                    { 371L, "DOBELE", 106L, "Dobele" },
                    { 372L, "JAUNBERZES_PAG", 106L, "Jaunbērzes pag." },
                    { 386L, "LAPMEZCIEMA_PAG", 110L, "Lapmežciema pag." },
                    { 373L, "PENKULES_PAG", 106L, "Penkules pag." },
                    { 375L, "ANNENIEKU_PAG", 106L, "Annenieku pag." },
                    { 376L, "BERZES_PAG", 106L, "Bērzes pag." },
                    { 377L, "AURU_PAG", 106L, "Auru pag." },
                    { 378L, "DOBELES_PAG", 106L, "Dobeles pag." },
                    { 379L, "KRIMUNU_PAG", 106L, "Krimūnu pag." },
                    { 380L, "BIKSTU_PAG", 106L, "Bikstu pag." },
                    { 381L, "ZEBRENES_PAG", 106L, "Zebrenes pag." },
                    { 382L, "DUNDAGAS_PAG", 108L, "Dundagas pag." },
                    { 383L, "KOLKAS_PAG", 108L, "Kolkas pag." },
                    { 384L, "DUNDAGA", 108L, "Dundaga" },
                    { 374L, "NAUDITES_PAG", 106L, "Naudītes pag." },
                    { 310L, "PINKI", 88L, "Piņķi" },
                    { 309L, "SALAS_PAG", 88L, "Salas pag." },
                    { 308L, "BABITE", 88L, "Babīte" },
                    { 234L, "MALIENAS_PAG", 68L, "Malienas pag." },
                    { 235L, "KALNCEMPJU_PAG", 68L, "Kalncempju pag." },
                    { 236L, "MARKALNES_PAG", 68L, "Mārkalnes pag." },
                    { 237L, "ILZENES_PAG", 68L, "Ilzenes pag." },
                    { 238L, "ANNAS_PAG", 68L, "Annas pag." },
                    { 239L, "ZELTINU_PAG", 68L, "Zeltiņu pag." },
                    { 240L, "APE", 70L, "Ape" },
                    { 241L, "GAUJIENAS_PAG", 70L, "Gaujienas pag." },
                    { 242L, "VIRESU_PAG", 70L, "Virešu pag." },
                    { 243L, "TRAPENES_PAG", 70L, "Trapenes pag." },
                    { 233L, "JAUNLAICENES_PAG", 68L, "Jaunlaicenes pag." },
                    { 244L, "APES_PAG", 70L, "Apes pag." },
                    { 246L, "INDRANU_PAG", 72L, "Indrānu pag." },
                    { 247L, "ADAZI", 74L, "Ādaži" },
                    { 248L, "ILKENE", 74L, "Iļķene" },
                    { 249L, "ALDERI", 74L, "Alderi" },
                    { 250L, "ANI", 74L, "Āņi" },
                    { 251L, "GARKALNE", 74L, "Garkalne" },
                    { 252L, "STAPRINI", 74L, "Stapriņi" },
                    { 253L, "ATARI", 74L, "Atari" },
                    { 254L, "DIVEZERI", 74L, "Divezeri" },
                    { 255L, "BIRZNIEKI", 74L, "Birznieki" },
                    { 245L, "LUBANA", 72L, "Lubāna" },
                    { 256L, "EIMURI", 74L, "Eimuri" },
                    { 232L, "VECLAICENES_PAG", 68L, "Veclaicenes pag." },
                    { 230L, "JAUNANNAS_PAG", 68L, "Jaunannas pag." },
                    { 208L, "ASARES_PAG", 62L, "Asares pag." },
                    { 209L, "STAICELE", 64L, "Staicele" },
                    { 210L, "ALOJA", 64L, "Aloja" },
                    { 211L, "BRASLAVAS_PAG", 64L, "Braslavas pag." },
                    { 212L, "BRIVZEMNIEKU_PAG", 64L, "Brīvzemnieku pag." },
                    { 213L, "STAICELES_PAG", 64L, "Staiceles pag." },
                    { 214L, "ALOJAS_PAG", 64L, "Alojas pag." },
                    { 215L, "DIENVIDSTACIJA", 66L, "Dienvidstacija" },
                    { 216L, "REGI", 66L, "Reģi" },
                    { 217L, "GRAVERI", 66L, "Grāveri" },
                    { 231L, "LIEPNAS_PAG", 68L, "Liepnas pag." },
                    { 218L, "BERZKALNI", 66L, "Bērzkalni" },
                    { 220L, "BUCMANCIEMS", 66L, "Būcmaņciems" },
                    { 221L, "ALMALE", 66L, "Almāle" },
                    { 222L, "ALSUNGA", 66L, "Alsunga" },
                    { 223L, "BALANDE", 66L, "Balande" },
                    { 224L, "ALUKSNE", 68L, "Alūksne" },
                    { 225L, "MāLUPES_PAG", 68L, "Mālupes pag." },
                    { 226L, "PADEDZES_PAG", 68L, "Pededzes pag." },
                    { 227L, "JAUNALUKSNES_PAG", 68L, "Jaunalūksnes pag." },
                    { 228L, "ZIEMERA_PAG", 68L, "Ziemera pag." },
                    { 229L, "ALSVIKU_PAG", 68L, "Alsviķu pag." },
                    { 219L, "ZIEDLEJAS", 66L, "Ziedlejas" },
                    { 823L, "SALASPILS", 238L, "Salaspils" },
                    { 257L, "KADAGA", 74L, "Kadaga" },
                    { 259L, "CARNIKAVA", 76L, "Carnikava" },
                    { 286L, "VALGALCIEMS", 80L, "Valgalciems" },
                    { 287L, "PURCIEMS", 80L, "Pūrciems" },
                    { 288L, "KALTENE", 80L, "Kaltene" },
                    { 289L, "APSUCIEMS", 80L, "Apšuciems" },
                    { 290L, "RUDE", 80L, "Rude" },
                    { 291L, "GIPKA", 80L, "Ģipka" },
                    { 292L, "UPESGRIVA", 82L, "Upesgrīva" },
                    { 293L, "ALKSNAJI", 82L, "Alksnāji" },
                    { 294L, "KIPATI", 82L, "Ķipati" },
                    { 295L, "MERSRAGS", 82L, "Mērsrags" },
                    { 285L, "AIZKLANI", 80L, "Aizklāņi" },
                    { 296L, "BALDONE", 84L, "Baldone" },
                    { 298L, "AVOTI", 84L, "Avoti" },
                    { 299L, "AUCE", 86L, "Auce" },
                    { 300L, "BENES_PAG", 86L, "Bēnes pag." },
                    { 301L, "ILES_PAG", 86L, "Īles pag." },
                    { 302L, "VITINU_PAG", 86L, "Vītiņu pag." },
                    { 303L, "VECAUCES_PAG", 86L, "Vecauces pag." },
                    { 304L, "LIELAUCES_PAG", 86L, "Lielauces pag." },
                    { 305L, "UKRU_PAG", 86L, "Ukru pag." },
                    { 306L, "BENE", 86L, "Bēne" },
                    { 307L, "BABITES_PAG", 88L, "Babītes pag." },
                    { 297L, "BALDONES_PAG", 84L, "Baldones pag." },
                    { 258L, "BALTEZERS", 74L, "Baltezers" },
                    { 284L, "ZOCENE", 80L, "Žocene" },
                    { 282L, "ROJA", 80L, "Roja" },
                    { 260L, "GAUJA", 76L, "Gauja" },
                    { 261L, "GARCIEMS", 76L, "Garciems" },
                    { 262L, "SIGULI", 76L, "Siguļi" },
                    { 263L, "EIMURI", 76L, "Eimuri" },
                    { 264L, "MEZCIEMS_CARNIKAVAS", 76L, "Mežciems" },
                    { 265L, "LAVERI", 76L, "Laveri" },
                    { 266L, "LILASTE", 76L, "Lilaste" },
                    { 267L, "GARUPE", 76L, "Garupe" },
                    { 268L, "MEZGARCIEMS", 76L, "Mežgarciems" },
                    { 269L, "KALNGALE", 76L, "Kalngale" },
                    { 283L, "MELNSILS", 80L, "Melnsils" },
                    { 270L, "BALTEZERS_GARKALNES", 78L, "Baltezers" },
                    { 272L, "AMATNIEKI", 78L, "Amatnieki" },
                    { 273L, "PRIEDKALNE", 78L, "Priedkalne" },
                    { 274L, "GARKALNE_GARKALNES", 78L, "Garkalne" },
                    { 275L, "SUZI", 78L, "Suži" },
                    { 276L, "SKUKISI", 78L, "Skuķīši" },
                    { 277L, "MAKSTENIEKI", 78L, "Makstenieki" },
                    { 278L, "PRIEZLEJAS", 78L, "Priežlejas" },
                    { 279L, "SUNISI", 78L, "Sunīši" },
                    { 280L, "LANGSTINI", 78L, "Langstiņi" },
                    { 281L, "BUKULTI_GARKALNES", 78L, "Bukulti" },
                    { 271L, "UPESCIEMS", 78L, "Upesciems" },
                    { 824L, "SALASPILS_PAG", 238L, "Salaspils pag." }
                });

            migrationBuilder.CreateIndex(
                name: "IX_City_CountyId",
                table: "City",
                column: "CountyId");

            migrationBuilder.CreateIndex(
                name: "IX_Comment_CustomerId",
                table: "Comment",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Comment_PropertyId",
                table: "Comment",
                column: "PropertyId");

            migrationBuilder.CreateIndex(
                name: "IX_Comment_TransactionId",
                table: "Comment",
                column: "TransactionId");

            migrationBuilder.CreateIndex(
                name: "IX_Comment_UserId",
                table: "Comment",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Contact_CustomerId",
                table: "Contact",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Contact_PropertyId",
                table: "Contact",
                column: "PropertyId");

            migrationBuilder.CreateIndex(
                name: "IX_Customer_UserId",
                table: "Customer",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Photo_PropertyId",
                table: "Photo",
                column: "PropertyId");

            migrationBuilder.CreateIndex(
                name: "IX_Property_CityId",
                table: "Property",
                column: "CityId");

            migrationBuilder.CreateIndex(
                name: "IX_Property_CountyId",
                table: "Property",
                column: "CountyId");

            migrationBuilder.CreateIndex(
                name: "IX_Property_UserId",
                table: "Property",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Transaction_CustomerId",
                table: "Transaction",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Transaction_PropertyId",
                table: "Transaction",
                column: "PropertyId");

            migrationBuilder.CreateIndex(
                name: "IX_Transaction_UserId",
                table: "Transaction",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_User_UserName",
                table: "User",
                column: "UserName",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Comment");

            migrationBuilder.DropTable(
                name: "Contact");

            migrationBuilder.DropTable(
                name: "Photo");

            migrationBuilder.DropTable(
                name: "Transaction");

            migrationBuilder.DropTable(
                name: "Customer");

            migrationBuilder.DropTable(
                name: "Property");

            migrationBuilder.DropTable(
                name: "City");

            migrationBuilder.DropTable(
                name: "User");

            migrationBuilder.DropTable(
                name: "County");
        }
    }
}
